### ISSUE TITLE
Doesn't appear to be working anymore with TinyMCE 7

### ISSUE THREAD

**Issue by hostep** [Magenerds/PageDesigner#54]
After upgrading Magento from 2.4.7-p2 to 2.4.7-p3 (which comes with a upgrade of TinyMCE 5 to 7, what were they thinking 🙄), if you open a cms page that already has content in the backoffice and then open the 'Content' tab, the page designer fails to initialise properly and we see this error message in the console:

```
Uncaught (in promise) TypeError: tinymce.activeEditor.plugins.magentowidget.encodeWidgets is not a function
    at mageWidgetEncode (page_designer.js:35:63)
    at Object.<anonymous> (page_designer.js:373:69)
    at Function.each (jquery.js:383:35)
    at jQuery.fn.init.each (jquery.js:205:27)
    at Object.<anonymous> (page_designer.js:370:40)
    at Function.each (jquery.js:383:35)
    at jQuery.fn.init.each (jquery.js:205:27)
    at pageDesigner.importWithPreviews (page_designer.js:369:34)
    at UiClass.<anonymous> (page_designer.js:112:35)
    at page_designer.js:88:29
```

I know that you guys no longer support this module, but I'm getting quite desperate as some of our clients do still have this module installed and now no longer can edit their content anymore after the latest security patch update of Magento.

Can somebody give me a hint if this would be easily solvable?
We already tried for 2-3 hours with 2 persons to figure out a solution to fix this in code, but we are failing hard.
Some hints would be greatly appreciated.

Many thanks! :)

**Comment by hostep** [comment]
Found the problem, it's a bug introduced in some Magento code: https://github.com/magento/magento2/pull/39258
